# Generated by Django 3.1.5 on 2021-02-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=250)),
                ('abrev', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='', max_length=8)),
            ],
        ),
    ]
