# Generated by Django 3.1.5 on 2021-03-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=250)),
                ('nom', models.CharField(max_length=250)),
                ('adress', models.TextField()),
                ('tel', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=250)),
                ('profile_image', models.ImageField(blank=True, default='login.png', null=True, upload_to='users/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.person')),
            ],
        ),
    ]
