# Generated by Django 3.1.5 on 2021-02-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('adress', models.TextField()),
                ('tel', models.CharField(max_length=10)),
            ],
        ),
    ]
