# Generated by Django 3.1.5 on 2021-03-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='profile_image',
            new_name='image',
        ),
    ]
