# Generated by Django 3.1.5 on 2021-03-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210305_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.person')),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('mere', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.mere')),
                ('pere', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.pere')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.person')),
            ],
        ),
    ]
