# Generated by Django 3.1.5 on 2021-02-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210204_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('nom', models.CharField(blank=True, max_length=250)),
                ('telephone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=200)),
                ('statut', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.departement')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.poste')),
            ],
        ),
    ]
