# Generated by Django 3.1.5 on 2021-03-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_enfant_mere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pere',
            name='person',
        ),
        migrations.AddField(
            model_name='pere',
            name='Pere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.person'),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='mere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.mere'),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='pere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.pere'),
        ),
        migrations.AlterField(
            model_name='mere',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.person'),
        ),
    ]
