# Generated by Django 3.1.5 on 2021-02-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_classe_ecole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='ecole',
        ),
    ]
