# Generated by Django 3.1.5 on 2021-03-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210306_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='genre',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='', max_length=250),
        ),
    ]
