# Generated by Django 3.1.5 on 2021-03-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20210307_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='genre',
            field=models.CharField(choices=[('HOMME', 'HOMME'), ('FEMME', 'FEMME')], default='', max_length=250),
        ),
    ]
