# Generated by Django 3.1.5 on 2021-03-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20210307_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='stat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mere',
            name='stat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pere',
            name='stat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='stat',
            field=models.BooleanField(default=True),
        ),
    ]
