# Generated by Django 3.1.7 on 2021-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20210308_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='users/login.png', null=True, upload_to='users/'),
        ),
    ]
