# Generated by Django 3.1.7 on 2021-03-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20210323_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gene',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
