# Generated by Django 3.1.7 on 2021-04-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_person_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='datedeces',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='datenaiss',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lieudeces',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lieunaiss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gene',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
