# Generated by Django 3.1.7 on 2021-03-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_person_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gene',
            field=models.IntegerField(),
        ),
    ]
