# Generated by Django 3.1.7 on 2021-04-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20210409_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
