# Generated by Django 3.1.5 on 2021-03-01 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_inscription_montant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('mois', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.eleve')),
            ],
        ),
    ]
