# Generated by Django 3.1.7 on 2021-03-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20210328_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gene',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
