# Generated by Django 3.1.5 on 2021-02-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='login.png', null=True, upload_to='users/'),
        ),
    ]
