# Generated by Django 3.1.5 on 2021-03-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_profile_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
