# Generated by Django 3.1.7 on 2021-03-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stat',
            field=models.BooleanField(default=True),
        ),
    ]
