# Generated by Django 3.1.7 on 2021-04-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_customuser_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
